## modified form [zsh-docker-aliases](https://github.com/akarzim/zsh-docker-aliases)

alias --save dk='docker'
alias --save dka='docker attach'
alias --save dkb='docker build'
alias --save dkd='docker diff'
alias --save dkdf='docker system df'
alias --save dke='docker exec'
alias --save dkE='docker exec -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t'
alias --save dkh='docker history'
alias --save dki='docker images'
alias --save dkin='docker inspect'
alias --save dkim='docker import'
alias --save dkk='docker kill'
alias --save dkkh='docker kill -s HUP'
alias --save dkl='docker logs'
alias --save dkL='docker logs -f'
alias --save dkli='docker login'
alias --save dklo='docker logout'
alias --save dkls='docker ps'
alias --save dkp='docker pause'
alias --save dkP='docker unpause'
alias --save dkpl='docker pull'
alias --save dkph='docker push'
alias --save dkps='docker ps'
alias --save dkpsa='docker ps -a'
alias --save dkr='docker run'
alias --save dkR='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm'
alias --save dkRe='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm --entrypoint /bin/bash'
alias --save dkRM='docker system prune'
alias --save dkrm='docker rm'
alias --save dkrmi='docker rmi'
alias --save dkrn='docker rename'
alias --save dks='docker start'
alias --save dkS='docker restart'
alias --save dkss='docker stats'
alias --save dksv='docker save'
alias --save dkt='docker tag'
alias --save dktop='docker top'
alias --save dkup='docker update'
alias --save dkV='docker volume'
alias --save dkv='docker version'
alias --save dkw='docker wait'
alias --save dkx='docker stop'

## Container (C)
alias --save dkC='docker container'
alias --save dkCa='docker container attach'
alias --save dkCcp='docker container cp'
alias --save dkCd='docker container diff'
alias --save dkCe='docker container exec'
alias --save dkCE='docker container exec -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t'
alias --save dkCin='docker container inspect'
alias --save dkCk='docker container kill'
alias --save dkCl='docker container logs'
alias --save dkCL='docker container logs -f'
alias --save dkCls='docker container ls'
alias --save dkCp='docker container pause'
alias --save dkCpr='docker container prune'
alias --save dkCrn='docker container rename'
alias --save dkCS='docker container restart'
alias --save dkCrm='docker container rm'
alias --save dkCr='docker container run'
alias --save dkCR='docker container run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm'
alias --save dkCRe='docker container run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm --entrypoint /bin/bash'
alias --save dkCs='docker container start'
alias --save dkCss='docker container stats'
alias --save dkCx='docker container stop'
alias --save dkCtop='docker container top'
alias --save dkCP='docker container unpause'
alias --save dkCup='docker container update'
alias --save dkCw='docker container wait'

## Image (I)
alias --save dkI='docker image'
alias --save dkIb='docker image build'
alias --save dkIh='docker image history'
alias --save dkIim='docker image import'
alias --save dkIin='docker image inspect'
alias --save dkIls='docker image ls'
alias --save dkIpr='docker image prune'
alias --save dkIpl='docker image pull'
alias --save dkIph='docker image push'
alias --save dkIrm='docker image rm'
alias --save dkIsv='docker image save'
alias --save dkIt='docker image tag'

## Volume (V)
alias --save dkV='docker volume'
alias --save dkVin='docker volume inspect'
alias --save dkVls='docker volume ls'
alias --save dkVpr='docker volume prune'
alias --save dkVrm='docker volume rm'

## Network (N)
alias --save dkN='docker network'
alias --save dkNs='docker network connect'
alias --save dkNx='docker network disconnect'
alias --save dkNin='docker network inspect'
alias --save dkNls='docker network ls'
alias --save dkNpr='docker network prune'
alias --save dkNrm='docker network rm'

## System (Y)
alias --save dkY='docker system'
alias --save dkYdf='docker system df'
alias --save dkYpr='docker system prune'

## Stack (K)
alias --save dkK='docker stack'
alias --save dkKls='docker stack ls'
alias --save dkKps='docker stack ps'
alias --save dkKrm='docker stack rm'

## Swarm (W)
alias --save dkW='docker swarm'

## CleanUp (rm)
# Clean up exited containers (docker < 1.13)
alias --save dkrmC='docker rm $(docker ps -qaf status=exited)'

# Clean up dangling images (docker < 1.13)
alias --save dkrmI='docker rmi $(docker images -qf dangling=true)'

# Pull all tagged images
alias --save dkplI='docker images --format "{{ .Repository }}" | grep -v "^<none>$" | xargs -L1 docker pull'

# Clean up dangling volumes (docker < 1.13)
alias --save dkrmV='docker volume rm $(docker volume ls -qf dangling=true)'

# Docker Machine (m)
alias --save dkm='docker-machine'
alias --save dkma='docker-machine active'
alias --save dkmcp='docker-machine scp'
alias --save dkmin='docker-machine inspect'
alias --save dkmip='docker-machine ip'
alias --save dkmk='docker-machine kill'
alias --save dkmls='docker-machine ls'
alias --save dkmpr='docker-machine provision'
alias --save dkmps='docker-machine ps'
alias --save dkmrg='docker-machine regenerate-certs'
alias --save dkmrm='docker-machine rm'
alias --save dkms='docker-machine start'
alias --save dkmsh='docker-machine ssh'
alias --save dkmst='docker-machine status'
alias --save dkmS='docker-machine restart'
alias --save dkmu='docker-machine url'
alias --save dkmup='docker-machine upgrade'
alias --save dkmv='docker-machine version'
alias --save dkmx='docker-machine stop'

alias --save dkc='docker compose'
alias --save dkcb='docker compose build'
alias --save dkcB='docker compose build --no-cache'
alias --save dkccp='docker compose copy'
alias --save dkccr='docker compose create'
alias --save dkccv='docker compose convert'
alias --save dkcd='docker compose down'
alias --save dkce='docker compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias --save dkcev='docker compose events'
alias --save dkci='docker compose images'
alias --save dkck='docker compose kill'
alias --save dkcl='docker compose logs'
alias --save dkcL='docker compose logs -f'
alias --save dkcls='docker compose ls'
alias --save dkcp='docker compose pause'
alias --save dkcP='docker compose unpause'
alias --save dkcpl='docker compose pull'
alias --save dkcph='docker compose push'
alias --save dkcpo='docker compose port'
alias --save dkcps='docker compose ps'
alias --save dkcr='docker compose run -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias --save dkcR='docker compose run -e COLUMNS=`tput cols` -e LINES=`tput lines` --rm'
alias --save dkcrm='docker compose rm'
alias --save dkcs='docker compose start'
alias --save dkcsc='docker-compose scale'
alias --save dkcS='docker compose restart'
alias --save dkct='docker compose top'
alias --save dkcu='docker compose up'
alias --save dkcU='docker compose up -d'
alias --save dkcv='docker-compose version'
alias --save dkcx='docker compose stop'

# Mutagen
alias --save mg='mutagen'
alias --save mgc='mutagen compose'
alias --save mgcb='mutagen compose build'
alias --save mgcB='mutagen compose build --no-cache'
alias --save mgcd='mutagen compose down'
alias --save mgce='mutagen compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias --save mgck='mutagen compose kill'
alias --save mgcl='mutagen compose logs'
alias --save mgcL='mutagen compose logs -f'
alias --save mgcls='mutagen compose ps'
alias --save mgcp='mutagen compose pause'
alias --save mgcP='mutagen compose unpause'
alias --save mgcpl='mutagen compose pull'
alias --save mgcph='mutagen compose push'
alias --save mgcps='mutagen compose ps'
alias --save mgcr='mutagen compose run -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias --save mgcR='mutagen compose run -e COLUMNS=`tput cols` -e LINES=`tput lines` --rm'
alias --save mgcrm='mutagen compose rm'
alias --save mgcs='mutagen compose start'
alias --save mgcsc='mutagen compose scale'
alias --save mgcS='mutagen compose restart'
alias --save mgcu='mutagen compose up'
alias --save mgcU='mutagen compose up -d'
alias --save mgcv='mutagen compose version'
alias --save mgcx='mutagen compose stop'
 